-- Schema Structure Export
-- Generated on: 2025-07-16T17:22:22.525085

CREATE TABLE "alert_attachments" ("attachment_id" INTEGER NOT NULL DEFAULT nextval('alert_attachments_attachment_id_seq'::regclass), "alert_id" INTEGER, "file_name" VARCHAR(255) NOT NULL, "file_path" VARCHAR(255) NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "alert_audit" ("audit_id" INTEGER NOT NULL DEFAULT nextval('alert_audit_audit_id_seq'::regclass), "alert_id" INTEGER, "user_id" INTEGER, "action" VARCHAR(255), "details" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "alert_cstm_attributes" ("alert_id" NUMERIC NOT NULL, "pp_message" TEXT NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE, "created_by" VARCHAR(15) NOT NULL DEFAULT 'System'::character varying, "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE, "gi_message" TEXT, "last_updated_by" VARCHAR(15), "last_updated_date" TIMESTAMP WITHOUT TIME ZONE, "is_post_positive_completed" CHAR(1), "is_early_pp_completed" CHAR(1));

CREATE TABLE "alert_det" ("id" NUMERIC NOT NULL, "alert_id" NUMERIC NOT NULL, "field_name" VARCHAR(4000) NOT NULL, "field_name_alias" VARCHAR(100) NOT NULL, "field_value_offset" NUMERIC NOT NULL, "field_order" NUMERIC NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT ((clock_timestamp() AT TIME ZONE COALESCE(current_setting('aws_oracle_ext.tz'::text, true), 'UTC'::text)))::timestamp(0) without time zone, "last_updated_date" TIMESTAMP WITHOUT TIME ZONE, "created_by" VARCHAR(50) NOT NULL DEFAULT 'System'::character varying, "last_updated_by" VARCHAR(50), "version" NUMERIC, "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE, "field_value" VARCHAR(4000), "is_field_value_clob" CHAR(1));

CREATE TABLE "alert_details_mst" ("alert_detail_id" INTEGER NOT NULL DEFAULT nextval('alert_details_mst_alert_detail_id_seq'::regclass), "alert_id" INTEGER, "detail_description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE);

CREATE TABLE "alert_mst" ("id" NUMERIC NOT NULL, "source_system" VARCHAR(250) NOT NULL, "due_time" VARCHAR(50), "priority" NUMERIC, "alert_type" VARCHAR(500), "business_unit" VARCHAR(50) NOT NULL, "business_user" VARCHAR(20), "rule_set" VARCHAR(500), "txn_id" VARCHAR(250) NOT NULL, "last_updated_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_by" VARCHAR(50) NOT NULL DEFAULT 'System'::character varying, "last_updated_by" VARCHAR(50), "amount" NUMERIC, "hit_count" NUMERIC, "currency" VARCHAR(3), "replyto_queue_name" VARCHAR(50), "request_number" NUMERIC, "reply_to_manager" VARCHAR(500), "value_date" DATE, "branch" VARCHAR(500), "last_transaction_date" DATE, "closed_date" DATE, "qa_status" VARCHAR(50), "direction" VARCHAR(500), "receiver" VARCHAR(500), "systemid" VARCHAR(500), "remaining_sanctions_matches" NUMERIC, "steps" VARCHAR(50), "closed_by" VARCHAR(50), "origination_branch" VARCHAR(250), "origination_region" VARCHAR(250), "is_post_positive_completed" CHAR(1), "application_alias_name" VARCHAR(500), "unique_transaction_reference" VARCHAR(500), "country_origination" VARCHAR(500), "country_intermediary" VARCHAR(500), "country_destination" VARCHAR(500), "last_stage" VARCHAR(500), "screening_type" VARCHAR(500), "screening_category" VARCHAR(500), "sector" VARCHAR(500), "business_line" VARCHAR(500), "product" VARCHAR(500), "sub_product" VARCHAR(500), "local_reference" VARCHAR(500), "transaction_date" DATE, "sender_bic" VARCHAR(500), "receiver_bic" VARCHAR(500), "payment_currency" VARCHAR(500), "queue_transition_date" DATE, "qa_closed_by" VARCHAR(500), "header_version" CHAR(50), "inquiry_step_identifier" VARCHAR(50), "business_id" NUMERIC, "original_debtor_name" VARCHAR(500), "beneficiary_account" VARCHAR(500), "ordering_customer_account" VARCHAR(500), "product_code" VARCHAR(100), "secondary_site" VARCHAR(50), "derived_step_identifier" VARCHAR(250), "branch_txn_id" VARCHAR(250), "l3_dual_review" CHAR(3) DEFAULT 'No'::bpchar, "research_type" VARCHAR(500), "updated_final_decision" VARCHAR(50), "udf1_datetime" DATE, "screened_date" DATE, "org_citi_legal_vehicle" VARCHAR(750), "org_citi_legal_vehicle_type" VARCHAR(100), "dest_citi_legal_vehicle" VARCHAR(750), "dest_citi_legal_vehicle_type" VARCHAR(100), "dr_alert_id" NUMERIC, "uk_sanctions_authority" VARCHAR(50), "auto_dispose_matches" CHAR(1), "lapc_alert" VARCHAR(50), "citi_enabled" CHAR(1), "parent_alert_id" NUMERIC, "rescind_status" VARCHAR(50), "rmp_alert" VARCHAR(250), "rmp_prev_alertid" NUMERIC, "rmp_rules" VARCHAR(50), "rmp_csaw_instance" VARCHAR(50), "bulk_process_req_id" NUMERIC, "rtm_alert_id" NUMERIC, "is_urgent" CHAR(1) DEFAULT 'N'::bpchar, "partition_date" DATE NOT NULL, "step_identifier" VARCHAR(250), "classification" VARCHAR(250), "created_date" DATE);

CREATE TABLE "alert_notes" ("note_id" INTEGER NOT NULL DEFAULT nextval('alert_notes_note_id_seq'::regclass), "alert_id" INTEGER, "note_text" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "business_on_boarding" ("onboarding_id" INTEGER NOT NULL DEFAULT nextval('business_on_boarding_onboarding_id_seq'::regclass), "user_id" INTEGER, "unit_id" INTEGER, "start_date" DATE, "end_date" DATE, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "business_role" ("role_id" INTEGER NOT NULL DEFAULT nextval('business_role_role_id_seq'::regclass), "role_name" VARCHAR(255) NOT NULL, "description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "business_units" ("unit_id" INTEGER NOT NULL DEFAULT nextval('business_units_unit_id_seq'::regclass), "unit_name" VARCHAR(255) NOT NULL, "description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "business_user" ("user_id" INTEGER NOT NULL DEFAULT nextval('business_user_user_id_seq'::regclass), "username" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "email" VARCHAR(255), "role_id" INTEGER, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "enhanced_search_field_mst" ("field_name" VARCHAR(150), "description" VARCHAR(512), "data_type" VARCHAR(50), "limit" NUMERIC, "operators" VARCHAR(200), "field_size" NUMERIC, "table_name" VARCHAR(30), "column_name" VARCHAR(160), "query" VARCHAR(4000), "argument" VARCHAR(1000), "created_by" VARCHAR(50), "created_date" TIMESTAMP WITHOUT TIME ZONE, "icon" VARCHAR(150), "column_width" NUMERIC, "text_align" VARCHAR(30), "field_type" VARCHAR(30), "gui_identifier" VARCHAR(100), "component" VARCHAR(50), "is_editable" CHAR(1) NOT NULL, "inline_filter_type" VARCHAR(58), "display_order" NUMERIC, "ui_enable" CHAR(1) NOT NULL DEFAULT 'Y'::bpchar, "is_sortable" CHAR(1) NOT NULL DEFAULT 'N'::bpchar);

CREATE TABLE "enhanced_search_fields" ("field_group" VARCHAR(100) NOT NULL, "field_name" VARCHAR(100) NOT NULL, "field_type" VARCHAR(20) NOT NULL, "display_order" NUMERIC NOT NULL, "gui_identifier" VARCHAR(100) NOT NULL, "created_by" VARCHAR(50), "created_date" DATE, "updated_by" VARCHAR(50), "updated_date" DATE, "is_active" CHAR(1) NOT NULL, "partition_date" DATE, "is_sortable" CHAR(1) NOT NULL, "collection_name" VARCHAR(50), "regex_enabled" VARCHAR(1));

CREATE TABLE "gui_label" ("gui_identifier" VARCHAR(100) NOT NULL, "role_identifier" VARCHAR(100) NOT NULL, "label" VARCHAR(1000), "user_language" VARCHAR(100) NOT NULL);

CREATE TABLE "hit_match_detail" ("id" NUMERIC NOT NULL, "match_pattern_value" VARCHAR(700) NOT NULL, "hit_percentage" NUMERIC NOT NULL, "matchable_description" VARCHAR(4000), "category" VARCHAR(400), "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE, "created_by" VARCHAR(50) NOT NULL DEFAULT 'System'::character varying, "alert_det_id" NUMERIC NOT NULL, "offset" NUMERIC, "match_length" NUMERIC NOT NULL, "version" NUMERIC, "last_transitioned_by" VARCHAR(50), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE, "alert_id" NUMERIC, "hit_number" NUMERIC(40), "hit_type" VARCHAR(250), "match_text" VARCHAR(4000), "taxonomy_sub_taxonomy_id" NUMERIC, "coverage_area" VARCHAR(100), "specific_coverage_area" VARCHAR(255), "is_final_decision" CHAR(1) DEFAULT 'N'::bpchar, "hit_touch_count" NUMERIC(40), "confirmed_false_match" CHAR(1) DEFAULT 'N'::bpchar, "l3_escalation_not_required" CHAR(1) DEFAULT 'N'::bpchar, "category_lookup" VARCHAR(40), "rule_checksum" VARCHAR(40), "repair_checksum" VARCHAR(40), "l3_checker_required" CHAR(1) DEFAULT 'N'::bpchar, "is_default_taxonomy" CHAR(1) DEFAULT 'N'::bpchar, "last_updated_date" TIMESTAMP WITHOUT TIME ZONE, "add_matchable_description" VARCHAR(4000), "mid_type" VARCHAR(18), "list_entry_type" VARCHAR(50), "list_entry_type_mg" VARCHAR(50), "is_batch_disposed" CHAR(1), "bulk_process_req_id" INTEGER, "rule_engine_id" INTEGER);

CREATE TABLE "match_notes" ("match_note_id" INTEGER NOT NULL DEFAULT nextval('match_notes_match_note_id_seq'::regclass), "alert_detail_id" INTEGER, "note_text" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "notes_audit" ("audit_id" INTEGER NOT NULL DEFAULT nextval('notes_audit_audit_id_seq'::regclass), "note_id" INTEGER, "user_id" INTEGER, "action" VARCHAR(255), "details" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'::text), "partition_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE "partition_log" ("log_id" INTEGER NOT NULL DEFAULT nextval('partition_log_log_id_seq'::regclass), "log_timestamp" TIMESTAMP WITH TIME ZONE DEFAULT now(), "schema_name" TEXT, "table_name" TEXT, "log_level" TEXT, "message" TEXT, "details" TEXT);

CREATE TABLE "partition_table_list" ("id" INTEGER NOT NULL DEFAULT nextval('partition_table_list_id_seq'::regclass), "schema_name" TEXT NOT NULL, "table_name" TEXT NOT NULL, "partition_column" TEXT NOT NULL DEFAULT 'partition_date'::text, "partition_column_type" TEXT NOT NULL DEFAULT 'DATE'::text, "partition_interval" TEXT NOT NULL DEFAULT '1 day'::text, "premake" INTEGER NOT NULL DEFAULT 4, "retention_interval" TEXT, "retention_keep_table" BOOLEAN NOT NULL DEFAULT false, "retention_keep_index" BOOLEAN NOT NULL DEFAULT true, "add_partition_column_if_missing" BOOLEAN NOT NULL DEFAULT false, "create_partition_column_index" BOOLEAN NOT NULL DEFAULT true, "optimize_constraint_exclusion" BOOLEAN NOT NULL DEFAULT true, "inherit_privileges" BOOLEAN NOT NULL DEFAULT true, "job_name" TEXT, "cron_schedule" TEXT DEFAULT '0 1 * * *'::text, "enabled" BOOLEAN NOT NULL DEFAULT true, "last_run_status" TEXT, "last_run_timestamp" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now());

CREATE TABLE "search_config" ("id" INTEGER NOT NULL DEFAULT nextval('search_config_id_seq'::regclass), "table_name" VARCHAR(100), "column_name" VARCHAR(100), "search_type" VARCHAR(50));

CREATE TABLE "user_bu_map" ("user_identifier" VARCHAR(50) NOT NULL, "bu_identifier" VARCHAR(500) NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE, "created_by" VARCHAR(100));

-- Constraints
ALTER TABLE "alert_attachments" ADD CONSTRAINT "alert_attachments_pkey" PRIMARY KEY ("attachment_id");
ALTER TABLE "alert_audit" ADD CONSTRAINT "alert_audit_pkey" PRIMARY KEY ("audit_id");
ALTER TABLE "alert_details_mst" ADD CONSTRAINT "alert_details_mst_pkey" PRIMARY KEY ("alert_detail_id");
ALTER TABLE "alert_notes" ADD CONSTRAINT "alert_notes_pkey" PRIMARY KEY ("note_id");
ALTER TABLE "business_on_boarding" ADD CONSTRAINT "business_on_boarding_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "business_units"("unit_id");
ALTER TABLE "business_on_boarding" ADD CONSTRAINT "business_on_boarding_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "business_user"("user_id");
ALTER TABLE "business_on_boarding" ADD CONSTRAINT "business_on_boarding_pkey" PRIMARY KEY ("onboarding_id");
ALTER TABLE "business_role" ADD CONSTRAINT "business_role_pkey" PRIMARY KEY ("role_id");
ALTER TABLE "business_role" ADD CONSTRAINT "business_role_role_name_key" UNIQUE ("role_name");
ALTER TABLE "business_units" ADD CONSTRAINT "business_units_pkey" PRIMARY KEY ("unit_id");
ALTER TABLE "business_user" ADD CONSTRAINT "business_user_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "business_role"("role_id");
ALTER TABLE "business_user" ADD CONSTRAINT "business_user_pkey" PRIMARY KEY ("user_id");
ALTER TABLE "business_user" ADD CONSTRAINT "business_user_username_key" UNIQUE ("username");
ALTER TABLE "match_notes" ADD CONSTRAINT "match_notes_alert_detail_id_fkey" FOREIGN KEY ("alert_detail_id") REFERENCES "alert_details_mst"("alert_detail_id");
ALTER TABLE "match_notes" ADD CONSTRAINT "match_notes_pkey" PRIMARY KEY ("match_note_id");
ALTER TABLE "notes_audit" ADD CONSTRAINT "notes_audit_note_id_fkey" FOREIGN KEY ("note_id") REFERENCES "alert_notes"("note_id");
ALTER TABLE "notes_audit" ADD CONSTRAINT "notes_audit_pkey" PRIMARY KEY ("audit_id");
ALTER TABLE "partition_log" ADD CONSTRAINT "partition_log_pkey" PRIMARY KEY ("log_id");
ALTER TABLE "partition_table_list" ADD CONSTRAINT "partition_table_list_pkey" PRIMARY KEY ("id");
ALTER TABLE "partition_table_list" ADD CONSTRAINT "partition_table_list_schema_name_table_name_key" UNIQUE ("table_name");
ALTER TABLE "partition_table_list" ADD CONSTRAINT "partition_table_list_schema_name_table_name_key" UNIQUE ("table_name");
ALTER TABLE "partition_table_list" ADD CONSTRAINT "partition_table_list_schema_name_table_name_key" UNIQUE ("schema_name");
ALTER TABLE "partition_table_list" ADD CONSTRAINT "partition_table_list_schema_name_table_name_key" UNIQUE ("schema_name");
ALTER TABLE "search_config" ADD CONSTRAINT "search_config_pkey" PRIMARY KEY ("id");
ALTER TABLE "user_bu_map" ADD CONSTRAINT "user_bu_map_pk" PRIMARY KEY ("bu_identifier");
ALTER TABLE "user_bu_map" ADD CONSTRAINT "user_bu_map_pk" PRIMARY KEY ("user_identifier");
ALTER TABLE "user_bu_map" ADD CONSTRAINT "user_bu_map_pk" PRIMARY KEY ("bu_identifier");
ALTER TABLE "user_bu_map" ADD CONSTRAINT "user_bu_map_pk" PRIMARY KEY ("user_identifier");

